baseurl = "https://how-to-firebase.github.io/"
languageCode = "en-us"
title = "Fullstack Firebase"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir = "docs"

[params]
	# General information
	author = "Chris Esplin"
	description = "A series of Firebase tutorials"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/how-to-firebase/tutorials"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "ChrisEsplin"
	github  = "deltaepsilon"
	email   = "chris@chrisesplin.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[[menu.main]]
	name   = "Posts"
	url    = "posts/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
